version: '3'

services:
    web:
        build: .
        container_name: codeleague-cont
        restart: unless-stopped
        volumes:
            - .:/app
        ports:
            - "80:${DJANGO_PORT}"
        depends_on:
            - db
        env_file:
          - .env.sample
        command: sh ./docker-web-commands.sh

    db:
        build: ./postgresdata
        image: postgres:11
        container_name: postgres-cont
        volumes:
            # /host/path:/container/path
            - ./postgresdata/:/var/lib/postgresql/data/

volumes:
    postgresdata: